#!/usr/bin/env node
/**
 * Estlem — Setup Wizard
 *
 * Interactive script to switch the entire monorepo to a different
 * environment (production, vps, local, or a custom one) without
 * touching any code by hand.
 *
 * Usage:
 *   node scripts/setup-wizard.js
 *
 * What it does:
 *   1. Reads config/environments.json
 *   2. Asks which environment to activate (or create a new one)
 *   3. For custom env, prompts for each URL
 *   4. Writes all needed .env files for api/web/dashboard
 *   5. Updates the "active" field in environments.json
 *   6. Shows a summary of what changed
 *
 * Safe to re-run — does not delete any data, only rewrites env files.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(ROOT, 'config', 'environments.json');

const colors = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  blue: '\x1b[34m', cyan: '\x1b[36m',
};
const log = (msg, color = 'reset') => console.log(`${colors[color]}${msg}${colors.reset}`);

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

async function main() {
  log('\n╔══════════════════════════════════════════╗', 'cyan');
  log('║   Estlem — Environment Setup Wizard      ║', 'cyan');
  log('╚══════════════════════════════════════════╝\n', 'cyan');

  const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));

  log(`Currently active: ${colors.bold}${config.active}${colors.reset}`, 'green');
  log(`(${config.environments[config.active]?.label || 'unknown'})\n`, 'dim');

  // List environments
  log('Available environments:', 'bold');
  const keys = Object.keys(config.environments);
  keys.forEach((k, i) => {
    const env = config.environments[k];
    const marker = k === config.active ? '●' : '○';
    const color = k === config.active ? 'green' : 'reset';
    log(`  ${i + 1}. ${marker} ${k} — ${env.label}`, color);
  });
  log(`  ${keys.length + 1}. + Create new custom environment\n`, 'yellow');

  const choice = await ask(`Choose an environment (1-${keys.length + 1}): `);
  const choiceNum = parseInt(choice, 10);
  if (isNaN(choiceNum) || choiceNum < 1 || choiceNum > keys.length + 1) {
    log('Invalid choice. Aborted.', 'red');
    rl.close();
    return;
  }

  let envKey, envData;

  if (choiceNum === keys.length + 1) {
    // Create custom
    log('\n— Create New Environment —\n', 'yellow');
    envKey = (await ask('Environment key (e.g. staging): ')).trim();
    if (!envKey || config.environments[envKey]) {
      log('Invalid or duplicate key. Aborted.', 'red');
      rl.close();
      return;
    }
    const label = await ask('Label (description): ');
    const apiUrl = await ask('API base URL (e.g. https://api.example.com): ');
    const webUrl = await ask('Web URL (e.g. https://example.com): ');
    const dashboardUrl = await ask('Dashboard URL (e.g. https://dashboard.example.com): ');
    const dbUrl = await ask('DATABASE_URL (postgres://...): ');

    envData = {
      label,
      apiUrl: apiUrl.replace(/\/$/, ''),
      apiBase: `${apiUrl.replace(/\/$/, '')}/api/v1`,
      wsUrl: apiUrl.replace(/\/$/, '').replace(/^http/, 'http'),
      webUrl: webUrl.replace(/\/$/, ''),
      dashboardUrl: dashboardUrl.replace(/\/$/, ''),
      database: { provider: 'custom', connectionEnv: 'DATABASE_URL', url: dbUrl },
      deployment: {},
    };
    config.environments[envKey] = envData;
  } else {
    envKey = keys[choiceNum - 1];
    envData = config.environments[envKey];
  }

  log(`\nActivating: ${colors.bold}${envKey}${colors.reset}`, 'green');
  log(`  • API:       ${envData.apiUrl}`, 'dim');
  log(`  • Web:       ${envData.webUrl}`, 'dim');
  log(`  • Dashboard: ${envData.dashboardUrl}\n`, 'dim');

  const confirm = await ask('Proceed? (y/N): ');
  if (confirm.toLowerCase() !== 'y') {
    log('Aborted.', 'yellow');
    rl.close();
    return;
  }

  // Write env files
  log('\nWriting env files...', 'cyan');

  const webEnv = [
    `# Auto-generated by setup-wizard — active env: ${envKey}`,
    `NEXT_PUBLIC_API_URL=${envData.apiUrl}`,
    `NEXT_PUBLIC_WS_URL=${envData.wsUrl}`,
    '',
  ].join('\n');

  const dashEnv = [
    `# Auto-generated by setup-wizard — active env: ${envKey}`,
    `NEXT_PUBLIC_API_URL=${envData.apiUrl}`,
    `NEXT_PUBLIC_WS_URL=${envData.wsUrl}`,
    '',
  ].join('\n');

  const apiEnv = [
    `# Auto-generated by setup-wizard — active env: ${envKey}`,
    `NODE_ENV=${envKey === 'local' ? 'development' : 'production'}`,
    `PORT=${envData.deployment?.api?.port || 3001}`,
    `FRONTEND_URL=${envData.webUrl}`,
    `DASHBOARD_URL=${envData.dashboardUrl}`,
    envData.database?.url ? `DATABASE_URL=${envData.database.url}` : '# DATABASE_URL=...  (set in deploy platform)',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(ROOT, 'apps', 'web', '.env.local'), webEnv);
  log('  ✓ apps/web/.env.local', 'green');

  fs.writeFileSync(path.join(ROOT, 'apps', 'dashboard', '.env.local'), dashEnv);
  log('  ✓ apps/dashboard/.env.local', 'green');

  fs.writeFileSync(path.join(ROOT, 'apps', 'api', '.env'), apiEnv);
  log('  ✓ apps/api/.env', 'green');

  // Update active env in config
  config.active = envKey;
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n');
  log('  ✓ config/environments.json (active updated)', 'green');

  log('\n✅ Environment switched!', 'green');
  log('\nNext steps:', 'bold');
  log('  1. Rebuild: pnpm install && pnpm build');
  log('  2. Restart your dev servers / redeploy to the platform');
  log('  3. To rollback: node scripts/setup-wizard.js (pick another env)');
  log(`\nFor VPS-specific steps, see: docs/VPS-MIGRATION.md\n`, 'cyan');

  rl.close();
}

main().catch((e) => {
  console.error('Error:', e);
  rl.close();
  process.exit(1);
});
